#!/bin/bash

#sock5
export ALL_PROXY="socks5://127.0.0.1:10808"
export all_proxy="socks5://127.0.0.1:10808"

#http
export http_proxy="http://127.0.0.1:10809"
export HTTP_PROXY="http://127.0.0.1:10809"

#https
export https_proxy="https://127.0.0.1:10809"
export HTTPS_PROXY="https://127.0.0.1:10809"

env | grep -i proxy
