#!/bin/bash

if [ -z $1 ];then

	curl wttr.in/Tianjin\?format="%l:+%C+%c+%t+feels+like+%f,+wind:%w,+moon+tonight:+%m\n"

elif [ "$1" = "-f" ];then

	curl wttr.in/Tianjin

elif [ "$1" = "-d" ];then

	curl v2.wttr.in/Tianjin

elif [ "$1" ] && [ -z "$2" ];then

	curl wttr.in/$1\?format="%l:+%C+%c+%t+feels+like+%f,+wind:%w,+moon+tonight:+%m\n"

elif [ "$1" ] && [ "$2" = "-f" ];then

        curl wttr.in/$1

elif [ "$1" ] && [ "$2" = "-d" ];then

	 curl v2.wttr.in/$1

else echo "error"

fi
